AfterHoursTraderList = c(
  "Norris Ahmed",
  "Yasir B Al-Hassani",
  "John Anderson",
  "Robert Bailey",
  "John W Boring",
  "Tracy I Brown",
  "Shawn L. Bryant",
  "David W Butrow",
  "Mark Cavalier",
  "Jeffery Coates",
  "Keith Couch",
  "Jason Crouch",
  "Jr. Daschbach",
  "Vaughn Davies",
  "Kurt Duerod",
  "Deb Emerson",
  "Robert Etzel",
  "Spencer Goff",
  "Brian M Grizzle",
  "Kevin Grizzle",
  "Matthew Hughes",
  "Stuart Johnson",
  "Robert (Bob) Kline",
  "Steve Knapp",
  "Neil J Lagatare",
  "David J. Lamarca",
  "Stephanie Dawes Landry",
  "Kevin Libby",
  "David Lima",
  "Morris Mann",
  "Darryl McLamb",
  "James Merwald",
  "Michael Michalek",
  "Robert Odom",
  "Ryan C Peaper",
  "Matthew J Pessagno",
  "Timothy J Phillips",
  "Robert (Bob) Pleiss",
  "Scott S Rupprecht",
  "Ian Sachs",
  "Michael R Sanzo",
  "Donald Schopp",
  "Lori Simpson",
  "Edward B Steffe",
  "Troy Stevens",
  "Sean Thomas",
  "Alex Werner",
  "Raymond Wetzel",
  "Steven Wofford",
  "Michael Worthington",
  "James R Young",
  "Procmon",
  "E44616" # Tracy I Brown
  
  )

