/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gs_secdb_ProfileView_ProfileAnalyzer */

#ifndef _Included_com_gs_secdb_ProfileView_ProfileAnalyzer
#define _Included_com_gs_secdb_ProfileView_ProfileAnalyzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NumNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NumNodes
  (JNIEnv *, jobject);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodesByTime
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodesByTime
  (JNIEnv *, jobject);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodesByTotalTime
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodesByTotalTime
  (JNIEnv *, jobject);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodesByObject
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodesByObject
  (JNIEnv *, jobject);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeShortText
 * Signature: (IZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeShortText
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeVisits
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeVisits
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeTime
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeTime
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeChildrenTime
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeChildrenTime
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeChildren
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeChildren
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeChildrenTimes
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeChildrenTimes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeFillInInfo
 * Signature: (Lcom/gs/secdb/ProfileView/ProfileNode;I)V
 */
JNIEXPORT void JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeFillInInfo
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    Analyze
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_Analyze
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    NodeMapDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_NodeMapDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gs_secdb_ProfileView_ProfileAnalyzer
 * Method:    AnalyzerInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gs_secdb_ProfileView_ProfileAnalyzer_AnalyzerInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
