/****************************************************************
**
**	BASE.H	- 
**
**	Copyright 2001 - Goldman, Sachs & Co. - New York
**
**	$Header: /home/cvs/src/gsutil/src/gsutil/base.h,v 1.4 2001/08/16 14:55:57 walkerpa Exp $
**
****************************************************************/

#if !defined( IN_GSUTIL_BASE_H )
#define IN_GSUTIL_BASE_H

CC_BEGIN_NAMESPACE( Gs )

#ifdef  BUILDING_GSUTIL
#define EXPORT_C_GSUTIL		EXPORT_C_EXPORT
#define EXPORT_CPP_GSUTIL		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSUTIL	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_GSUTIL		EXPORT_C_IMPORT
#define EXPORT_CPP_GSUTIL		EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSUTIL	EXPORT_CLASS_IMPORT
#endif

#ifdef  BUILDING_GSXMLUTIL
#define EXPORT_C_GSXMLUTIL		EXPORT_C_EXPORT
#define EXPORT_CPP_GSXMLUTIL		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSXMLUTIL	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_GSXMLUTIL		EXPORT_C_IMPORT
#define EXPORT_CPP_GSXMLUTIL		EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSXMLUTIL	EXPORT_CLASS_IMPORT
#endif

#ifdef  BUILDING_GSXMLDT
#define EXPORT_C_GSXMLDT		EXPORT_C_EXPORT
#define EXPORT_CPP_GSXMLDT		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSXMLDT	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_GSXMLDT		EXPORT_C_IMPORT
#define EXPORT_CPP_GSXMLDT		EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSXMLDT	EXPORT_CLASS_IMPORT
#endif

#ifdef  BUILDING_GSUTILSYSMON
#define EXPORT_C_GSUTILSYSMON		EXPORT_C_EXPORT
#define EXPORT_CPP_GSUTILSYSMON		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSUTILSYSMON	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_GSUTILSYSMON		EXPORT_C_IMPORT
#define EXPORT_CPP_GSUTILSYSMON		EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSUTILSYSMON	EXPORT_CLASS_IMPORT
#endif

CC_END_NAMESPACE

#endif 
