/****************************************************************
**
**	SDB_ERR.H	
**
**	Copyright 1993 - Goldman, Sachs & Co. - New York
**
**	$Header: /home/cvs/src/secdb/src/sdb_err.h,v 1.10 2000/06/07 14:03:20 goodfj Exp $
**
****************************************************************/

#include <secerror.h>

	REGISTER_ERR( ERR_UNKNOWN					);
	REGISTER_ERR( ERR_INVALID_ARGUMENTS			);
	REGISTER_ERR( ERR_INVALID_CHARACTER			);
	REGISTER_ERR( ERR_INVALID_NUMBER			);
	REGISTER_ERR( ERR_INVALID_STRING			);
	REGISTER_ERR( ERR_MEMORY					);
	REGISTER_ERR( ERR_UNSUPPORTED_OPERATION		);
	REGISTER_ERR( ERR_DIVIDE_BY_ZERO			);
	REGISTER_ERR( ERR_OVERFLOW					);
	REGISTER_ERR( ERR_UNDERFLOW					);
	REGISTER_ERR( ERR_INCOMPLETE				);
	REGISTER_ERR( ERR_NOTHING_CHANGED	  		);
	REGISTER_ERR( ERR_NOT_FOUND		 			);
	REGISTER_ERR( ERR_NOT_STARTED				);
	REGISTER_ERR( ERR_NOT_CONSISTENT	 		);
	REGISTER_ERR( ERR_VERSION_MISMATCH			);
	REGISTER_ERR( ERR_FILE_INVALID				);
	REGISTER_ERR( ERR_FILE_FAILURE  			);
	REGISTER_ERR( ERR_FILE_READ_ONLY			);
	REGISTER_ERR( ERR_FILE_NOT_FOUND			);
	REGISTER_ERR( ERR_FILE_IN_USE   			);
	REGISTER_ERR( ERR_FILE_ALREADY_EXISTS		);
	REGISTER_ERR( ERR_FILE_MODIFIED				);
	REGISTER_ERR( ERR_DATABASE_INVALID			);
	REGISTER_ERR( ERR_DATABASE_FAILURE  		);
	REGISTER_ERR( ERR_DATABASE_READ_ONLY		);
	REGISTER_ERR( ERR_DATABASE_NOT_FOUND		);
	REGISTER_ERR( ERR_DATABASE_IN_USE   		);
	REGISTER_ERR( ERR_DATABASE_ALREADY_EXISTS	);
	REGISTER_ERR( ERR_DATABASE_MODIFIED	 		);
	REGISTER_ERR( ERR_DATABASE_OBSOLETE			);
	REGISTER_ERR( ERR_NETWORK_FAILURE			);
	REGISTER_ERR( ERR_CONNECTION_LOST			);
	REGISTER_ERR( ERR_CONNECTION_FAILURE		);
	REGISTER_ERR( ERR_WOULD_BLOCK				);
	REGISTER_ERR( ERR_HOST_NOT_FOUND			);
	REGISTER_ERR( ERR_TIMEOUT					);

	REGISTER_SDB( ERR_CHILD_LIST_NOT_FOUND	, "Child list not found" );
	REGISTER_SDB( ERR_GET_VALUE_ABORTED		, "GetValue aborted" );
	REGISTER_SDB( ERR_OBJECT_INVALID		, "Object invalid" );
	REGISTER_SDB( ERR_OBJECT_NOT_FOUND	  	, "Object not found" );
	REGISTER_SDB( ERR_OBJECT_ALREADY_EXISTS	, "Object already exists" );
	REGISTER_SDB( ERR_OBJECT_MODIFIED	  	, "Object modified" );
	REGISTER_SDB( ERR_OBJECT_IN_USE		  	, "Object in use" );
	REGISTER_SDB( ERR_CLASS_FAILURE			, "Class failure" );
	REGISTER_SDB( ERR_CLASS_NOT_FOUND		, "Class not found" );
	REGISTER_SDB( ERR_TRANSACTION_FAILURE	, "Transaction failure" );
	REGISTER_SDB( ERR_LOCK_TIMEOUT			, "Lock timeout" );
	REGISTER_SDB( ERR_LOCK_FAILURE  		, "Lock failure" );
	REGISTER_SDB( ERR_INDEX_INVALID 		, "Index invalid" );
	REGISTER_SDB( ERR_INDEX_FAILURE	 		, "Index failure" );
	REGISTER_SDB( ERR_INDEX_NOT_FOUND 		, "Index not found" );
	REGISTER_SDB( ERR_INDEX_ALREADY_EXISTS	, "Index already exists" );
	REGISTER_SDB( ERR_NOT_NEEDED			, "Not needed" );

	REGISTER_SDB( ERR_SLANG_EVAL			, "Slang evaluation error" );
	REGISTER_SDB( ERR_SLANG_ARG				, "Slang arguments error" );

	REGISTER_SDB( ERR_VALUE_CHANGED			, "Value changed while using it as a child" );
	REGISTER_SDB( ERR_CYCLE_DETECTED		, "Cycle was detected" );
	REGISTER_SDB( ERR_INVALIDATING_LOCKED_VALUE, "Value was invalidated while it was calculating" );
