/* $Header: /home/cvs/src/gsdtlite/src/gsdt/base.h,v 1.3 2001/11/27 22:45:04 procmon Exp $ */
/****************************************************************
**
**	gsdt/base.h	- The base file for the GsDt class heirarchy
**
**	Copyright 1998 - Goldman, Sachs & Co. - New York
**
**	$Header: /home/cvs/src/gsdtlite/src/gsdt/base.h,v 1.3 2001/11/27 22:45:04 procmon Exp $
**
****************************************************************/

#if !defined( IN_GSDT_BASE_H )
#define IN_GSDT_BASE_H

#ifdef BUILDING_GSDTLITE
#define EXPORT_C_GSDTLITE			EXPORT_C_EXPORT
#define EXPORT_CPP_GSDTLITE			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSDTLITE		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_GSDTLITE	EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_GSDTLITE			EXPORT_C_IMPORT
#define EXPORT_CPP_GSDTLITE			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSDTLITE		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_GSDTLITE	EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_X_GSDTLITE
#define EXPORT_C_X_GSDTLITE		EXPORT_C_EXPORT
#define EXPORT_CPP_X_GSDTLITE	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_X_GSDTLITE	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_X_GSDTLITE		EXPORT_C_IMPORT
#define EXPORT_CPP_X_GSDTLITE	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_X_GSDTLITE	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_GSDT
#define EXPORT_C_GSDT			EXPORT_C_EXPORT
#define EXPORT_CPP_GSDT			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSDT		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_GSDT	EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_GSDT			EXPORT_C_IMPORT
#define EXPORT_CPP_GSDT			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSDT		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_GSDT	EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_GSDT_TEMPLATES
#undef EXPORT_TEMPLATE_GSDT
#define EXPORT_TEMPLATE_GSDT	EXPORT_TEMPLATE_BUILD
#endif

#ifdef BUILDING_X_GSDT
#define EXPORT_C_X_GSDT		EXPORT_C_EXPORT
#define EXPORT_CPP_X_GSDT	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_X_GSDT	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_X_GSDT		EXPORT_C_IMPORT
#define EXPORT_CPP_X_GSDT	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_X_GSDT	EXPORT_CLASS_IMPORT
#endif


#endif

