################################################################################
# This file is useful for dynamically generating a condor submission file for
# a given R Script. All that is required is a job name and an input file path.
#
# You can also pass an optional section that adds your own specific information
# to the file.
#
# The only function that should be called from this script is:
#   GenerateCondorFile$writeCondorFile( jobName, inputFilePath, individualJobPortion )
#

################################################################################
# File Namespace
#
GenerateCondorFile = new.env(hash=TRUE)


################################################################################
# This produces the actual output file needed to run the condor jobs
#
# Return - an array of strings to be written to the condor submit file
#
GenerateCondorFile$writeCondorFile <- function(jobName, condorOutputPath, 
        inputFilePath, individualJobPortion="Queue", retryOnError=FALSE, 
        machine=NULL, linesToAppend=NULL)
{
    inputFilePath = gsub("/", "\\\\", inputFilePath) 
    individualJobPortion = gsub("/", "\\\\", individualJobPortion)
    
    fileOutput = GenerateCondorFile$.generateStandardCondorHeader( jobName, 
            inputFilePath, retryOnError, machine, linesToAppend )
    
    fileOutput = append(fileOutput, individualJobPortion)
    
    write(fileOutput,file=condorOutputPath)
    cat("Wrote file:", condorOutputPath, "\n")
    
    return(condorOutputPath)
}

################################################################################
# This produces the standard heading for the Condor submit file.
#
# Return - an array of strings to be written to the condor submit file
#
GenerateCondorFile$.generateStandardCondorHeader <- function(jobName, 
        inputFilePath, retryOnError=FALSE, machine=NULL, linesToAppend=NULL)
{
    fileOutput = "# WARNING: THIS FILE WAS AUTOGENERATED. CHANGES WILL BE LOST NEXT TIME IT IS PRODUCED!"
    fileOutput = append(fileOutput, "# Run the R script generateCondorSubmitFile.R instead")
    fileOutput = append(fileOutput, " ")
    fileOutput = append(fileOutput, "#Begin Standard Header ")
    fileOutput = append(fileOutput, paste("JobName =", jobName) )
    fileOutput = append(fileOutput, "LogHeader = $(JobName).$(Cluster).$(Process).$$(Machine)")
    
    fileOutput = append( fileOutput, 
            GenerateCondorFile$.getRHeaderInformation(jobName, inputFilePath) )
    
    fileOutput = append(fileOutput, "transfer_executable = False")
    fileOutput = append(fileOutput, "should_transfer_files = No")
    fileOutput = append(fileOutput, "getenv = True")
    fileOutput = append(fileOutput, "EnvSettings = TMP=C:\\temp TEMP=C:\\temp")
    fileOutput = append(fileOutput, "run_as_owner = true")
    
    machineString = NULL
    if( !is.null(machine) )
    {
        machineString = paste( ' && Machine == "', machine, '"', sep="")
    }
    requirementLine = paste( 'Requirements = UidDomain == "Ceg.Corp.Net"', 
            '&& FileSystemDomain == "Ceg.Corp.Net"', machineString )
    fileOutput = append(fileOutput, requirementLine )
    
    fileOutput = append(fileOutput, "Universe = vanilla")
    
    if(retryOnError)
    {
        fileOutput = append(fileOutput, "on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)")
    }
    
    for( line in linesToAppend )
    {
        fileOutput = append(fileOutput, line) 
    }
    
    fileOutput = append(fileOutput, " ")
    
    return( fileOutput )
}


################################################################################
# This produces the R 2.5 heading for the Condor submit file.
#
GenerateCondorFile$.getRHeaderInformation <- function(jobName, inputFilePath)
{
    fileOutput = " "
    fileOutput = append(fileOutput, paste("input =",inputFilePath) )
    fileOutput = append(fileOutput, "output = \\\\ceg\\cershare\\All\\Risk\\Reports\\VaR\\prod\\CondorNightlyLogs\\$(LogHeader).out")
    fileOutput = append(fileOutput, "error = \\\\ceg\\cershare\\All\\Risk\\Reports\\VaR\\prod\\CondorNightlyLogs\\$(LogHeader).error")
    fileOutput = append(fileOutput, paste("log = \\\\ceg\\cershare\\All\\Risk\\Reports\\VaR\\prod\\CondorNightlyLogs\\",jobName,".log",sep=""))
    
    fileOutput = append(fileOutput, "executable = $ENV(SystemRoot)\\system32\\cmd.exe")
    fileOutput = append(fileOutput, "arguments = /Q /C \\\\ceg\\cershare\\All\\Risk\\Software\\R\\prod\\Utilities\\Environment\\Condor\\RunR.bat")
    fileOutput = append(fileOutput, " ")
    
    return(fileOutput)
}

