/****************************************************************
**
**	fcadlib/base.h	- Base header for fcadlib libraries
**
**	Copyright 1998 - Goldman, Sachs & Co. - New York
**
**	$Header: /home/cvs/src/fcadlib/src/fcadlib/base.h,v 1.5 2001/11/27 21:41:48 procmon Exp $
**
****************************************************************/

#if !defined( IN_FCADLIB_BASE_H )
#define IN_FCADLIB_BASE_H


/*
**	GSEXCEL - Goldman Excel addin loader
*/

#ifdef BUILDING_GSEXCEL
#define EXPORT_C_GSEXCEL			EXPORT_C_EXPORT
#define EXPORT_CPP_GSEXCEL			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_GSEXCEL		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_GSEXCEL		EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_GSEXCEL			EXPORT_C_IMPORT
#define EXPORT_CPP_GSEXCEL			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_GSEXCEL		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_GSEXCEL		EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_GSEXCEL_TEMPLATES
#undef EXPORT_TEMPLATE_GSEXCEL
#define EXPORT_TEMPLATE_GSEXCEL		EXPORT_TEMPLATE_BUILD
#endif


/*
**	FCADLIB - common adlib functionality
*/

#ifdef BUILDING_FCADLIB
#define EXPORT_C_FCADLIB			EXPORT_C_EXPORT
#define EXPORT_CPP_FCADLIB			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_FCADLIB		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_FCADLIB		EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_FCADLIB			EXPORT_C_IMPORT
#define EXPORT_CPP_FCADLIB			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_FCADLIB		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_FCADLIB		EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_FCADLIB_TEMPLATES
#undef EXPORT_TEMPLATE_FCADLIB
#define EXPORT_TEMPLATE_FCADLIB		EXPORT_TEMPLATE_BUILD
#endif


/*
**	FCADLIBX - Excel adlib
*/

#ifdef BUILDING_FCADLIBX
#define EXPORT_C_FCADLIBX			EXPORT_C_EXPORT
#define EXPORT_CPP_FCADLIBX			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_FCADLIBX		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_FCADLIBX	EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_FCADLIBX			EXPORT_C_IMPORT
#define EXPORT_CPP_FCADLIBX			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_FCADLIBX		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_FCADLIBX	EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_FCADLIBX_TEMPLATES
#undef EXPORT_TEMPLATE_FCADLIBX
#define EXPORT_TEMPLATE_FCADLIBX	EXPORT_TEMPLATE_BUILD
#endif


/*
**	FCADLIBS - Slang adlib
*/

#ifdef BUILDING_FCADLIBS
#define EXPORT_C_FCADLIBS			EXPORT_C_EXPORT
#define EXPORT_CPP_FCADLIBS			EXPORT_CPP_EXPORT
#define EXPORT_CLASS_FCADLIBS		EXPORT_CLASS_EXPORT
#define EXPORT_TEMPLATE_FCADLIBS	EXPORT_TEMPLATE_EXPORT
#else
#define EXPORT_C_FCADLIBS			EXPORT_C_IMPORT
#define EXPORT_CPP_FCADLIBS			EXPORT_CPP_IMPORT
#define EXPORT_CLASS_FCADLIBS		EXPORT_CLASS_IMPORT
#define EXPORT_TEMPLATE_FCADLIBS	EXPORT_TEMPLATE_IMPORT
#endif

#ifdef BUILDING_FCADLIBS_TEMPLATES
#undef EXPORT_TEMPLATE_FCADLIBS
#define EXPORT_TEMPLATE_FCADLIBS	EXPORT_TEMPLATE_BUILD
#endif


#endif

