/****************************************************************
**
**	Copyright 1999 - Goldman, Sachs & Co. - New York
**
**	$Header: /home/cvs/src/quant/src/q_base.h,v 1.7 2001/11/27 23:13:44 procmon Exp $
**
****************************************************************/

#if !defined( IN_Q_BASE_H )
#define IN_Q_BASE_H

#ifdef BUILDING_QUANT
#define EXPORT_C_QUANT		EXPORT_C_EXPORT
#define EXPORT_CPP_QUANT	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QUANT	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QUANT		EXPORT_C_IMPORT
#define EXPORT_CPP_QUANT	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QUANT	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QWRAP
#define EXPORT_C_QWRAP		EXPORT_C_EXPORT
#define EXPORT_CPP_QWRAP	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QWRAP	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QWRAP		EXPORT_C_IMPORT
#define EXPORT_CPP_QWRAP	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QWRAP	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QKNOCK
#define EXPORT_C_QKNOCK		EXPORT_C_EXPORT
#define EXPORT_CPP_QKNOCK	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QKNOCK	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QKNOCK		EXPORT_C_IMPORT
#define EXPORT_CPP_QKNOCK	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QKNOCK	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QFADE
#define EXPORT_C_QFADE		EXPORT_C_EXPORT
#define EXPORT_CPP_QFADE	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QFADE	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QFADE		EXPORT_C_IMPORT
#define EXPORT_CPP_QFADE	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QFADE	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QAMORT
#define EXPORT_C_QAMORT		EXPORT_C_EXPORT
#define EXPORT_CPP_QAMORT	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QAMORT	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QAMORT		EXPORT_C_IMPORT
#define EXPORT_CPP_QAMORT	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QAMORT	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QOILOPT
#define EXPORT_C_QOILOPT   	EXPORT_C_EXPORT
#define EXPORT_CPP_QOILOPT	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QOILOPT	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QOILOPT	EXPORT_C_IMPORT
#define EXPORT_CPP_QOILOPT	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QOILOPT	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QMRM
#define EXPORT_C_QMRM		EXPORT_C_EXPORT
#define EXPORT_CPP_QMRM		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QMRM	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QMRM		EXPORT_C_IMPORT
#define EXPORT_CPP_QMRM	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QMRM	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QWINGS
#define EXPORT_C_QWINGS		EXPORT_C_EXPORT
#define EXPORT_CPP_QWINGS	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QWINGS	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QWINGS		EXPORT_C_IMPORT
#define EXPORT_CPP_QWINGS	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QWINGS	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QRARE
#define EXPORT_C_QRARE		EXPORT_C_EXPORT
#define EXPORT_CPP_QRARE	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QRARE	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QRARE		EXPORT_C_IMPORT
#define EXPORT_CPP_QRARE	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QRARE	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QBASIC
#define EXPORT_C_QBASIC		EXPORT_C_EXPORT
#define EXPORT_CPP_QBASIC	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QBASIC	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QBASIC		EXPORT_C_IMPORT
#define EXPORT_CPP_QBASIC	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QBASIC	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QEXOTIC
#define EXPORT_C_QEXOTIC	EXPORT_C_EXPORT
#define EXPORT_CPP_QEXOTIC	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QEXOTIC	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QEXOTIC	EXPORT_C_IMPORT
#define EXPORT_CPP_QEXOTIC	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QEXOTIC	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_QAVG
#define EXPORT_C_QAVG		EXPORT_C_EXPORT
#define EXPORT_CPP_QAVG		EXPORT_CPP_EXPORT
#define EXPORT_CLASS_QAVG	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_QAVG		EXPORT_C_IMPORT
#define EXPORT_CPP_QAVG		EXPORT_CPP_IMPORT
#define EXPORT_CLASS_QAVG	EXPORT_CLASS_IMPORT
#endif

#ifdef BUILDING_Q3FAC
#define EXPORT_C_Q3FAC		EXPORT_C_EXPORT
#define EXPORT_CPP_Q3FAC	EXPORT_CPP_EXPORT
#define EXPORT_CLASS_Q3FAC	EXPORT_CLASS_EXPORT
#else
#define EXPORT_C_Q3FAC		EXPORT_C_IMPORT
#define EXPORT_CPP_Q3FAC	EXPORT_CPP_IMPORT
#define EXPORT_CLASS_Q3FAC	EXPORT_CLASS_IMPORT
#endif

#endif 
