//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QuantLib {

public enum SEXPTYPE {
  NILSXP = 0,
  SYMSXP = 1,
  LISTSXP = 2,
  CLOSXP = 3,
  ENVSXP = 4,
  PROMSXP = 5,
  LANGSXP = 6,
  SPECIALSXP = 7,
  BUILTINSXP = 8,
  CHARSXP = 9,
  LGLSXP = 10,
  INTSXP = 13,
  REALSXP = 14,
  CPLXSXP = 15,
  STRSXP = 16,
  DOTSXP = 17,
  ANYSXP = 18,
  VECSXP = 19,
  EXPRSXP = 20,
  BCODESXP = 21,
  EXTPTRSXP = 22,
  WEAKREFSXP = 23,
  RAWSXP = 24,
  S4SXP = 25,
  NEWSXP = 30,
  FREESXP = 31,
  FUNSXP = 99
}

}
