/** DO NOT DELETE THIS LINE! Janified_by_janify Wed Jan 12 11:41:08 2000 **/

#ifndef _FIMATHRECIPESEXPORT_H
#define _FIMATHRECIPESEXPORT_H

#ifdef BUILDING_FIMATHRECIPES
# define EXPORT_CLASS_FIMATHRECIPES EXPORT_CLASS_EXPORT
# define EXPORT_CPP_FIMATHRECIPES EXPORT_CPP_EXPORT
# define EXPORT_C_FIMATHRECIPES EXPORT_C_EXPORT
#else
# define EXPORT_CLASS_FIMATHRECIPES EXPORT_CLASS_IMPORT
# define EXPORT_CPP_FIMATHRECIPES EXPORT_CPP_IMPORT
# define EXPORT_C_FIMATHRECIPES EXPORT_C_IMPORT
#endif /* ifdef BUILDING_FIMATHRECIPES */

#endif /* #ifndef _FIMATHRECIPESEXPORT_H */
